sudo: required
language: node_js
node_js:
  - "4.2.6"
before_install:  
- curl https://install.meteor.com/ | sh
services:
  - mongodb
# before_script:
#   - meteor --test --release velocity:METEOR@1.1.0.2_2